#include "gba.h"
#include "logic.h"
#include "draw.h"
// TA-TODO: Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>


#include "images/bird.h"
#include "images/square.h"
#include "images/start.h"

// AppState enum definition
typedef enum {
    // TA-TODO: Add any additional states you need for your app.
    START,
    START_NODRAW,
    APP_INIT,
    APP,
    APP_EXIT,
    APP_EXIT_NODRAW,
} GBAState;

int main(void) {
    volatile bool a_down = false;
    // TA-TODO: Manipulate REG_DISPCNT here to set Mode 3.
    REG_DISPCNT = MODE3 | BG2_ENABLE;

    GBAState state = START;

    // We store the "previous" and "current" states.
    AppState currentAppState, nextAppState;

    // We store the current and previous values of the button input.
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

    while (1) {
        // Load the current state of the buttons
        currentButtons = BUTTONS;

        // TA-TODO: Manipulate the state machine below as needed.
        switch(state) {
            case START:
                // Wait for VBlank
                waitForVBlank();

                // TA-TODO: Draw the start state here.
                drawFullScreenImageDMA(start);

                drawString(7, 10, "Shoot a bird", BLACK);
                drawString(90, 120, "Press A to start, reset!", BLACK);
                drawString(90, 140, "Press B to shoot a bird!", BLACK);

                state = START_NODRAW;
                break;
            case START_NODRAW:
                // TA-TODO: Check for a button press here to start the app.
                // Start the app by switching the state to APP_INIT.
                if (!a_down && KEY_DOWN(BUTTON_A, currentButtons)) {
                    fillScreenDMA(BLACK);
                    a_down = true;
                    state = APP_INIT;
                }
                if (a_down && !KEY_DOWN(BUTTON_A, currentButtons)) {
                    a_down = false;
                }
                
                break;

            case APP_INIT:
                // Initialize the app. Switch to the APP state.
                initializeAppState(&currentAppState);
                // drawString(10, 20, ("Score: "), BLACK);

                // Draw the initial state of the app
                fullDrawAppState(&currentAppState);
                
                state = APP;
                break;
            case APP:
                // Process the app for one frame, store the next state
                nextAppState = processAppState(&currentAppState, previousButtons, currentButtons);
                //check scores

                // Wait for VBlank before we do any drawing.
                waitForVBlank();

                // Undraw the previous state
                undrawAppState(&currentAppState);

                // Draw the current state
                drawAppState(&nextAppState);

                // Now set the current state as the next state for the next iter.
                currentAppState = nextAppState;

                if (!a_down && KEY_DOWN(BUTTON_A, currentButtons)) {
                    a_down = true;
                    state = START;
                }
                if (a_down && !KEY_DOWN(BUTTON_A, currentButtons)) {
                    a_down = false;
                }

                // Check if the app is exiting. If it is, then go to the exit state.
                if (nextAppState.gameOver == 1) {
                    state = APP_EXIT;
                }

                break;
            case APP_EXIT:
                // Wait for VBlank
                waitForVBlank();

                // TA-TODO: Draw the exit / gameover screen
                fullDrawAppState(&currentAppState);

                state = APP_EXIT_NODRAW;
                break;
            case APP_EXIT_NODRAW:
                // TA-TODO: Check for a button press here to go back to the start screen
                if (!a_down && KEY_DOWN(BUTTON_A, currentButtons)) {
                    a_down = true;
                    state = START;
                }
                if (a_down && !KEY_DOWN(BUTTON_A, currentButtons)) {
                    a_down = false;
                }

                break;
        }

        // Store the current state of the buttons
        previousButtons = currentButtons;
    }

    return 0;
}
